### ISSUE TITLE
Link to source from doc

### ISSUE THREAD

**Issue by manuranga** [ballerina-lang/docerina#140]
There should be a link to the source code git from the doc.

**Comment by lankavitharana** [comment]
Created a new issue in repository - https://github.com/ballerina-lang/ballerina
issue - https://github.com/ballerina-lang/ballerina/issues/4777
hence closing this issue

**Comment by manuranga** [comment]
Eg : if you go to https://docs.rs/tokio/0.2.1/tokio/io/struct.Error.html you can see `[Src]` link that will take you to the source code. Similar link should be available in https://ballerina.io/learn/api-docs/ballerina/io/index.html
