### ISSUE TITLE
at service level docerina tags are not read

### ISSUE THREAD

**Issue by shavantha** [ballerina-lang/docerina#99]
at the service level, Ballerina does not allow single line comments. However, docerina tags are allowed. However, it seems that tags such as @doc:Description are not shown once the docerina templates are generated.

steps
1.add a tag such as below just above the service.
@doc:Description { value: "The service helps to obtain the jacoco code coverage via jenkins as json payload"}

2.run the command to generate the doc template
../../../ballerina-tools-0.88/bin/ballerina doc ../../../wso2/ -o doc/   -v

Note: Ideally since the @doc:Description,  is allowed, the contents should be read. Currently, developers cannot add a single line comment nor does the docerina contents are shown for a service.

**Comment by lankavitharana** [comment]
Created a new issue in repository - https://github.com/ballerina-lang/ballerina
issue - ballerina-lang/ballerina#4781
hence closing this issue
